// ============================================================
// DATAGLOW — Tests: Institutional Memory Layer
// ============================================================
// Plain node, no DOM/DuckDB/network needed — js/memory/institutional-memory.js
// is pure JS with no browser APIs. Covers store shape, immutable append,
// query filtering, summarization, timeline generation, provenance hashing,
// pruning, merge/dedup, and NDJSON round-tripping (including malformed-line
// tolerance), matching the pattern used in test/ai-touch-ledger.test.mjs.

import assert from 'node:assert/strict';
import {
  RECORD_TYPES,
  MEMORY_STORE_VERSION,
  createMemoryStore,
  appendRecord,
  queryRecords,
  summarizeMemory,
  generateTimeline,
  computeProvenanceHash,
  pruneStore,
  mergeStores,
  exportNDJSON,
  importNDJSON,
} from '../../js/memory/institutional-memory.js';

let pass = 0, fail = 0;
async function test(name, fn) {
  try {
    await fn();
    pass++;
    console.log(`  ok - ${name}`);
  } catch (e) {
    fail++;
    console.log(`  FAIL - ${name}`);
    console.log(`    ${e.stack || e.message}`);
  }
}

// Small helper to build a valid record body without id/timestamp (those are
// auto-generated by appendRecord).
function rec(overrides = {}) {
  return {
    type: RECORD_TYPES.MANUAL_EDIT,
    actor: 'human',
    datasetId: 'claims-2026',
    ...overrides,
  };
}

// A tiny sleep to guarantee distinguishable timestamps where ordering matters.
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// ---- createMemoryStore ----

await test('createMemoryStore returns correct shape', () => {
  const store = createMemoryStore();
  assert.equal(Array.isArray(store.records), true);
  assert.equal(store.records.length, 0);
  assert.equal(store.version, MEMORY_STORE_VERSION);
  assert.equal(typeof store.createdAt, 'string');
  assert.doesNotThrow(() => new Date(store.createdAt).toISOString());
  assert.equal(typeof store.sessionId, 'string');
});

await test('createMemoryStore accepts an explicit sessionId', () => {
  const store = createMemoryStore({ sessionId: 'fixed-session' });
  assert.equal(store.sessionId, 'fixed-session');
});

await test('createMemoryStore generates distinct sessionIds across calls', () => {
  const a = createMemoryStore();
  const b = createMemoryStore();
  assert.notEqual(a.sessionId, b.sessionId);
});

// ---- appendRecord ----

await test('appendRecord adds a record with auto-generated id and timestamp', () => {
  const store = createMemoryStore();
  const next = appendRecord(store, rec({ type: RECORD_TYPES.AGENT_FIX_ACCEPTED, actor: 'agent' }));
  assert.equal(next.records.length, 1);
  const r = next.records[0];
  assert.equal(typeof r.id, 'string');
  assert.ok(r.id.length > 0);
  assert.equal(typeof r.timestamp, 'string');
  assert.doesNotThrow(() => new Date(r.timestamp).toISOString());
  assert.equal(r.type, RECORD_TYPES.AGENT_FIX_ACCEPTED);
  assert.equal(r.actor, 'agent');
});

await test('appendRecord assigns sessionId from store when not provided on record', () => {
  const store = createMemoryStore({ sessionId: 'sess-xyz' });
  const next = appendRecord(store, rec());
  assert.equal(next.records[0].sessionId, 'sess-xyz');
});

await test('appendRecord generates distinct ids for records appended in rapid succession', () => {
  let store = createMemoryStore();
  store = appendRecord(store, rec());
  store = appendRecord(store, rec());
  store = appendRecord(store, rec());
  const ids = store.records.map((r) => r.id);
  assert.equal(new Set(ids).size, 3);
});

await test('appendRecord is immutable — original store unchanged', () => {
  const store = createMemoryStore();
  const next = appendRecord(store, rec());
  assert.equal(store.records.length, 0);
  assert.equal(next.records.length, 1);
  assert.notEqual(store, next);
  assert.notEqual(store.records, next.records);
});

await test('appendRecord throws on invalid type', () => {
  const store = createMemoryStore();
  assert.throws(() => appendRecord(store, rec({ type: 'not_a_real_type' })));
});

await test('appendRecord throws on invalid actor', () => {
  const store = createMemoryStore();
  assert.throws(() => appendRecord(store, rec({ actor: 'robot' })));
});

await test('appendRecord throws when store is not a plain object', () => {
  assert.throws(() => appendRecord(null, rec()));
  assert.throws(() => appendRecord([], rec()));
});

await test('appendRecord preserves optional fields (column, before, after, reason, sql, metadata)', () => {
  const store = createMemoryStore();
  const next = appendRecord(store, rec({
    type: RECORD_TYPES.TYPE_OVERRIDDEN,
    column: 'claim_amount',
    before: 'string',
    after: 'number',
    reason: 'analyst confirmed numeric type',
    metadata: { source: 'canvas' },
  }));
  const r = next.records[0];
  assert.equal(r.column, 'claim_amount');
  assert.equal(r.before, 'string');
  assert.equal(r.after, 'number');
  assert.equal(r.reason, 'analyst confirmed numeric type');
  assert.deepEqual(r.metadata, { source: 'canvas' });
});

// ---- queryRecords ----

function buildMixedStore() {
  let store = createMemoryStore({ sessionId: 'mixed' });
  store = appendRecord(store, rec({ type: RECORD_TYPES.AGENT_FIX_ACCEPTED, actor: 'agent', datasetId: 'ds1', column: 'claim_amount', metadata: { count: 847 } }));
  store = appendRecord(store, rec({ type: RECORD_TYPES.AGENT_FIX_DISMISSED, actor: 'agent', datasetId: 'ds1', column: 'dob' }));
  store = appendRecord(store, rec({ type: RECORD_TYPES.MANUAL_EDIT, actor: 'human', datasetId: 'ds1', column: 'claim_amount', row: 42 }));
  store = appendRecord(store, rec({ type: RECORD_TYPES.VALIDATION_RESOLVED, actor: 'human', datasetId: 'ds2', column: 'npi' }));
  store = appendRecord(store, rec({ type: RECORD_TYPES.SQL_QUERY, actor: 'human', datasetId: 'ds1', sql: 'SELECT COUNT(*) FROM claims WHERE claim_amount < 0', metadata: { rowCount: 12 } }));
  store = appendRecord(store, rec({ type: RECORD_TYPES.STORY_EXPORTED, actor: 'human', datasetId: 'ds1', metadata: { title: 'Q3 Claims Review' } }));
  return store;
}

await test('queryRecords filters by type', () => {
  const store = buildMixedStore();
  const results = queryRecords(store, { type: RECORD_TYPES.MANUAL_EDIT });
  assert.equal(results.length, 1);
  assert.equal(results[0].type, RECORD_TYPES.MANUAL_EDIT);
});

await test('queryRecords filters by actor', () => {
  const store = buildMixedStore();
  const results = queryRecords(store, { actor: 'agent' });
  assert.equal(results.length, 2);
  assert.ok(results.every((r) => r.actor === 'agent'));
});

await test('queryRecords filters by datasetId', () => {
  const store = buildMixedStore();
  const results = queryRecords(store, { datasetId: 'ds2' });
  assert.equal(results.length, 1);
  assert.equal(results[0].datasetId, 'ds2');
});

await test('queryRecords filters by column', () => {
  const store = buildMixedStore();
  const results = queryRecords(store, { column: 'claim_amount' });
  assert.equal(results.length, 2);
  assert.ok(results.every((r) => r.column === 'claim_amount'));
});

await test('queryRecords filters by time range', async () => {
  let store = createMemoryStore();
  store = appendRecord(store, rec({ type: RECORD_TYPES.FILE_LOADED }));
  await sleep(20);
  const midpoint = new Date().toISOString();
  await sleep(20);
  store = appendRecord(store, rec({ type: RECORD_TYPES.SQL_QUERY, sql: 'SELECT 1' }));

  const before = queryRecords(store, { toTimestamp: midpoint });
  const after = queryRecords(store, { fromTimestamp: midpoint });
  assert.equal(before.length, 1);
  assert.equal(before[0].type, RECORD_TYPES.FILE_LOADED);
  assert.equal(after.length, 1);
  assert.equal(after[0].type, RECORD_TYPES.SQL_QUERY);
});

await test('queryRecords respects limit', () => {
  const store = buildMixedStore();
  const results = queryRecords(store, { datasetId: 'ds1', limit: 2 });
  assert.equal(results.length, 2);
});

await test('queryRecords returns newest first', async () => {
  let store = createMemoryStore();
  store = appendRecord(store, rec({ type: RECORD_TYPES.FILE_LOADED }));
  await sleep(5);
  store = appendRecord(store, rec({ type: RECORD_TYPES.SQL_QUERY, sql: 'SELECT 1' }));
  const results = queryRecords(store, {});
  assert.equal(results[0].type, RECORD_TYPES.SQL_QUERY);
  assert.equal(results[1].type, RECORD_TYPES.FILE_LOADED);
});

await test('queryRecords combines multiple filters (AND semantics)', () => {
  const store = buildMixedStore();
  const results = queryRecords(store, { datasetId: 'ds1', actor: 'agent' });
  assert.equal(results.length, 2);
  assert.ok(results.every((r) => r.datasetId === 'ds1' && r.actor === 'agent'));
});

await test('queryRecords returns empty array for a store with no records', () => {
  const store = createMemoryStore();
  assert.deepEqual(queryRecords(store, {}), []);
});

// ---- summarizeMemory ----

await test('summarizeMemory counts correctly across mixed record types', () => {
  const store = buildMixedStore();
  const summary = summarizeMemory(store, 'ds1');
  assert.equal(summary.totalDecisions, 5); // ds1 has 5 of the 6 records
  assert.equal(summary.agentFixes, 1);
  assert.equal(summary.humanEdits, 1);
  assert.equal(summary.dismissals, 1);
});

await test('summarizeMemory computes lastActivity as the most recent timestamp', () => {
  const store = buildMixedStore();
  const summary = summarizeMemory(store, 'ds1');
  const allTimestamps = store.records.filter((r) => r.datasetId === 'ds1').map((r) => r.timestamp);
  assert.equal(summary.lastActivity, allTimestamps.slice().sort().pop());
});

await test('summarizeMemory ranks topColumns by decision count descending', () => {
  const store = buildMixedStore();
  const summary = summarizeMemory(store, 'ds1');
  assert.ok(summary.topColumns.length > 0);
  assert.equal(summary.topColumns[0].column, 'claim_amount');
  assert.equal(summary.topColumns[0].decisionCount, 2);
});

await test('summarizeMemory across all datasets when datasetId omitted', () => {
  const store = buildMixedStore();
  const summary = summarizeMemory(store, undefined);
  assert.equal(summary.totalDecisions, 6);
});

await test('summarizeMemory on empty store returns zeroed counts', () => {
  const store = createMemoryStore();
  const summary = summarizeMemory(store, 'ds1');
  assert.equal(summary.totalDecisions, 0);
  assert.equal(summary.agentFixes, 0);
  assert.equal(summary.humanEdits, 0);
  assert.equal(summary.dismissals, 0);
  assert.equal(summary.validationsResolved, 0);
  assert.equal(summary.lastActivity, null);
  assert.deepEqual(summary.topColumns, []);
});

// ---- generateTimeline ----

await test('generateTimeline returns plain-language strings', () => {
  const store = buildMixedStore();
  const timeline = generateTimeline(store, 'ds1');
  assert.ok(timeline.length > 0);
  assert.ok(timeline.every((line) => typeof line === 'string'));
});

await test('generateTimeline includes count and column details for agent fixes', () => {
  const store = buildMixedStore();
  const timeline = generateTimeline(store, 'ds1', { includeTypes: [RECORD_TYPES.AGENT_FIX_ACCEPTED] });
  assert.equal(timeline.length, 1);
  assert.match(timeline[0], /847/);
  assert.match(timeline[0], /claim_amount/);
});

await test('generateTimeline describes SQL queries with the query text and row count', () => {
  const store = buildMixedStore();
  const timeline = generateTimeline(store, 'ds1', { includeTypes: [RECORD_TYPES.SQL_QUERY] });
  assert.equal(timeline.length, 1);
  assert.match(timeline[0], /SELECT COUNT\(\*\) FROM claims WHERE claim_amount < 0/);
  assert.match(timeline[0], /12 rows/);
});

await test('generateTimeline returns entries newest first', async () => {
  let store = createMemoryStore();
  store = appendRecord(store, rec({ type: RECORD_TYPES.FILE_LOADED, metadata: { fileName: 'claims.csv' } }));
  await sleep(5);
  store = appendRecord(store, rec({ type: RECORD_TYPES.STORY_EXPORTED, metadata: { title: 'Review' } }));
  const timeline = generateTimeline(store, 'claims-2026');
  assert.match(timeline[0], /Story/);
  assert.match(timeline[1], /File loaded/);
});

await test('generateTimeline respects maxEntries', () => {
  const store = buildMixedStore();
  const timeline = generateTimeline(store, 'ds1', { maxEntries: 2 });
  assert.equal(timeline.length, 2);
});

await test('generateTimeline respects actorFilter', () => {
  const store = buildMixedStore();
  const timeline = generateTimeline(store, 'ds1', { actorFilter: 'agent' });
  assert.equal(timeline.length, 2);
});

await test('generateTimeline respects includeTypes filter', () => {
  const store = buildMixedStore();
  const timeline = generateTimeline(store, 'ds1', { includeTypes: [RECORD_TYPES.MANUAL_EDIT] });
  assert.equal(timeline.length, 1);
  assert.match(timeline[0], /manually edited/);
});

await test('generateTimeline on empty store returns empty array', () => {
  const store = createMemoryStore();
  assert.deepEqual(generateTimeline(store, 'ds1'), []);
});

// ---- computeProvenanceHash ----

await test('computeProvenanceHash is deterministic for identical records', () => {
  const storeA = buildMixedStore();
  const storeB = buildMixedStore(); // fresh but structurally different ids/timestamps — test same store twice instead
  const hash1 = computeProvenanceHash(storeA, 'ds1');
  const hash2 = computeProvenanceHash(storeA, 'ds1');
  assert.equal(hash1, hash2);
  assert.equal(typeof hash1, 'string');
  assert.match(hash1, /^djb2:[0-9a-f]{8}$/);
});

await test('computeProvenanceHash differs when records differ', () => {
  const store = buildMixedStore();
  const hashBefore = computeProvenanceHash(store, 'ds1');
  const storeChanged = appendRecord(store, rec({ type: RECORD_TYPES.COLUMN_RENAMED, datasetId: 'ds1', before: 'amt', after: 'claim_amount' }));
  const hashAfter = computeProvenanceHash(storeChanged, 'ds1');
  assert.notEqual(hashBefore, hashAfter);
});

await test('computeProvenanceHash is order-independent for the same set of records', () => {
  let storeA = createMemoryStore({ sessionId: 's' });
  storeA = appendRecord(storeA, rec({ type: RECORD_TYPES.FILE_LOADED, datasetId: 'dsX' }));
  storeA = appendRecord(storeA, rec({ type: RECORD_TYPES.SQL_QUERY, datasetId: 'dsX', sql: 'SELECT 1' }));

  // Build the reverse-order variant by re-merging records in swapped order.
  const swapped = { ...storeA, records: [...storeA.records].reverse() };

  assert.equal(computeProvenanceHash(storeA, 'dsX'), computeProvenanceHash(swapped, 'dsX'));
});

await test('computeProvenanceHash on empty dataset returns a stable hash', () => {
  const store = createMemoryStore();
  const hash1 = computeProvenanceHash(store, 'nonexistent');
  const hash2 = computeProvenanceHash(createMemoryStore(), 'nonexistent');
  assert.equal(hash1, hash2);
});

// ---- pruneStore ----

await test('pruneStore respects maxRecords', () => {
  let store = createMemoryStore();
  for (let i = 0; i < 10; i++) {
    store = appendRecord(store, rec({ type: RECORD_TYPES.MANUAL_EDIT, column: `col${i}` }));
  }
  const pruned = pruneStore(store, { maxRecords: 3, keepTypes: [] });
  assert.equal(pruned.records.length, 3);
});

await test('pruneStore always keeps keepTypes even beyond maxRecords budget', () => {
  let store = createMemoryStore();
  store = appendRecord(store, rec({ type: RECORD_TYPES.FILE_LOADED, metadata: { fileName: 'a.csv' } }));
  for (let i = 0; i < 5; i++) {
    store = appendRecord(store, rec({ type: RECORD_TYPES.MANUAL_EDIT, column: `col${i}` }));
  }
  const pruned = pruneStore(store, { maxRecords: 2, keepTypes: ['file_loaded'] });
  const hasFileLoaded = pruned.records.some((r) => r.type === RECORD_TYPES.FILE_LOADED);
  assert.equal(hasFileLoaded, true);
});

await test('pruneStore keeps most recent records when over budget', async () => {
  let store = createMemoryStore();
  store = appendRecord(store, rec({ type: RECORD_TYPES.MANUAL_EDIT, column: 'old' }));
  await sleep(5);
  store = appendRecord(store, rec({ type: RECORD_TYPES.MANUAL_EDIT, column: 'new' }));
  const pruned = pruneStore(store, { maxRecords: 1, keepTypes: [] });
  assert.equal(pruned.records.length, 1);
  assert.equal(pruned.records[0].column, 'new');
});

await test('pruneStore returns a store with records sorted oldest-to-newest', async () => {
  let store = createMemoryStore();
  store = appendRecord(store, rec({ type: RECORD_TYPES.MANUAL_EDIT, column: 'a' }));
  await sleep(5);
  store = appendRecord(store, rec({ type: RECORD_TYPES.MANUAL_EDIT, column: 'b' }));
  const pruned = pruneStore(store, { maxRecords: 10 });
  assert.ok(pruned.records[0].timestamp <= pruned.records[1].timestamp);
});

await test('pruneStore on empty store returns empty records without throwing', () => {
  const store = createMemoryStore();
  const pruned = pruneStore(store, { maxRecords: 5 });
  assert.deepEqual(pruned.records, []);
});

// ---- mergeStores ----

await test('mergeStores deduplicates records with the same id', () => {
  let store = createMemoryStore({ sessionId: 'shared' });
  store = appendRecord(store, rec({ type: RECORD_TYPES.FILE_LOADED }));
  const storeA = store;
  const storeB = store; // same object reference — simulates two peers who haven't diverged yet
  const merged = mergeStores(storeA, storeB);
  assert.equal(merged.records.length, 1);
});

await test('mergeStores preserves full history from both peers when they diverge', () => {
  let base = createMemoryStore({ sessionId: 'base' });
  base = appendRecord(base, rec({ type: RECORD_TYPES.FILE_LOADED }));

  let peerA = appendRecord(base, rec({ type: RECORD_TYPES.MANUAL_EDIT, column: 'x' }));
  let peerB = appendRecord(base, rec({ type: RECORD_TYPES.MANUAL_EDIT, column: 'y' }));

  const merged = mergeStores(peerA, peerB);
  // base record (1) + peerA's unique edit (1) + peerB's unique edit (1) = 3
  assert.equal(merged.records.length, 3);
  assert.ok(merged.records.some((r) => r.column === 'x'));
  assert.ok(merged.records.some((r) => r.column === 'y'));
});

await test('mergeStores sorts merged records by timestamp', async () => {
  let peerA = createMemoryStore();
  peerA = appendRecord(peerA, rec({ type: RECORD_TYPES.FILE_LOADED }));
  await sleep(5);
  let peerB = createMemoryStore();
  peerB = appendRecord(peerB, rec({ type: RECORD_TYPES.SQL_QUERY, sql: 'SELECT 1' }));

  const merged = mergeStores(peerA, peerB);
  for (let i = 1; i < merged.records.length; i++) {
    assert.ok(merged.records[i - 1].timestamp <= merged.records[i].timestamp);
  }
});

await test('mergeStores handles empty stores gracefully', () => {
  const merged = mergeStores(createMemoryStore(), createMemoryStore());
  assert.deepEqual(merged.records, []);
});

// ---- exportNDJSON ----

await test('exportNDJSON produces one line per matching record', () => {
  const store = buildMixedStore();
  const ndjson = exportNDJSON(store, 'ds1');
  const lines = ndjson.split('\n').filter(Boolean);
  assert.equal(lines.length, 5);
  for (const line of lines) {
    assert.doesNotThrow(() => JSON.parse(line));
  }
});

await test('exportNDJSON without datasetId exports all records', () => {
  const store = buildMixedStore();
  const ndjson = exportNDJSON(store, undefined);
  const lines = ndjson.split('\n').filter(Boolean);
  assert.equal(lines.length, 6);
});

await test('exportNDJSON on empty store returns empty string', () => {
  const store = createMemoryStore();
  assert.equal(exportNDJSON(store, 'ds1'), '');
});

// ---- importNDJSON ----

await test('importNDJSON round-trips correctly', () => {
  const store = buildMixedStore();
  const ndjson = exportNDJSON(store, 'ds1');
  const imported = importNDJSON(ndjson);
  assert.equal(imported.records.length, 5);
  const originalIds = new Set(queryRecords(store, { datasetId: 'ds1' }).map((r) => r.id));
  for (const r of imported.records) {
    assert.ok(originalIds.has(r.id));
  }
});

await test('importNDJSON rejects malformed lines gracefully (skips, does not throw)', () => {
  const store = buildMixedStore();
  const validLine = JSON.stringify(store.records[0]);
  const ndjson = [
    validLine,
    '{not valid json',
    '',
    '   ',
    JSON.stringify({ id: 'x', type: 'bogus_type', actor: 'human', timestamp: new Date().toISOString() }),
    JSON.stringify({ id: 'y', actor: 'human', timestamp: new Date().toISOString() }), // missing type
  ].join('\n');

  let imported;
  assert.doesNotThrow(() => {
    imported = importNDJSON(ndjson);
  });
  assert.equal(imported.records.length, 1);
  assert.equal(imported.records[0].id, store.records[0].id);
});

await test('importNDJSON on empty/whitespace string returns an empty store', () => {
  const imported = importNDJSON('');
  assert.deepEqual(imported.records, []);
  const imported2 = importNDJSON('   \n  \n');
  assert.deepEqual(imported2.records, []);
});

await test('importNDJSON sorts imported records by timestamp', async () => {
  let store = createMemoryStore();
  store = appendRecord(store, rec({ type: RECORD_TYPES.FILE_LOADED }));
  await sleep(5);
  store = appendRecord(store, rec({ type: RECORD_TYPES.SQL_QUERY, sql: 'SELECT 1' }));

  // Export in normal order, then shuffle the NDJSON lines before importing.
  const ndjson = exportNDJSON(store, undefined);
  const shuffled = ndjson.split('\n').reverse().join('\n');
  const imported = importNDJSON(shuffled);

  assert.equal(imported.records[0].type, RECORD_TYPES.FILE_LOADED);
  assert.equal(imported.records[1].type, RECORD_TYPES.SQL_QUERY);
});

await test('importNDJSON rejects records with an invalid actor', () => {
  const line = JSON.stringify({ id: 'z', type: RECORD_TYPES.MANUAL_EDIT, actor: 'robot', timestamp: new Date().toISOString() });
  const imported = importNDJSON(line);
  assert.equal(imported.records.length, 0);
});

// ---- RECORD_TYPES sanity ----

await test('RECORD_TYPES exposes all eleven documented record kinds', () => {
  const expected = [
    'agent_fix_accepted', 'agent_fix_dismissed', 'manual_edit',
    'validation_resolved', 'validation_dismissed', 'sql_query',
    'story_exported', 'file_loaded', 'join_created',
    'column_renamed', 'type_overridden',
  ];
  assert.deepEqual(Object.values(RECORD_TYPES).sort(), expected.sort());
});

await test('RECORD_TYPES is frozen (cannot be mutated by callers)', () => {
  assert.throws(() => {
    RECORD_TYPES.NEW_TYPE = 'oops';
    if (Object.isFrozen(RECORD_TYPES)) throw new Error('frozen as expected');
  });
});

// ---- Summary ----

console.log(`\n${pass} passed, ${fail} failed`);
if (fail > 0) {
  process.exitCode = 1;
}
